# Generated by Django 6.0.2 on 2026-02-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0006_vehicle_is_featured_vehicle_slug_vehicle_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("birth_date", models.DateField()),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("independent", "Indépendant"),
                            ("student", "Étudiant"),
                            ("retired", "Retraité"),
                        ],
                        max_length=20,
                    ),
                ),
                ("employer", models.CharField(blank=True, max_length=150)),
                ("monthly_income", models.DecimalField(decimal_places=2, max_digits=8)),
                ("id_document", models.FileField(upload_to="reservations/id/")),
                (
                    "driving_license",
                    models.FileField(upload_to="reservations/license/"),
                ),
                (
                    "proof_of_address",
                    models.FileField(upload_to="reservations/address/"),
                ),
                ("income_proof", models.FileField(upload_to="reservations/income/")),
                ("rgpd_consent", models.BooleanField()),
                ("information_certified", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En cours de traitement"),
                            ("approved", "Validée"),
                            ("rejected", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
