# Generated by Django 6.0.2 on 2026-02-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="information_certified",
            new_name="accepted_gdpr",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="rgpd_consent",
            new_name="accepted_terms",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="driving_license",
            new_name="driver_license",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="employer",
        ),
        migrations.AddField(
            model_name="reservation",
            name="country",
            field=models.CharField(default="France", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="employment_status",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En cours de traitement"),
                    ("approved", "Validée"),
                    ("refused", "Refusée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
