# Generated by Django 6.0.2 on 2026-02-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "client",
            "0002_rename_information_certified_reservation_accepted_gdpr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="monthly_income",
        ),
    ]
