# Generated by Django 6.0.2 on 2026-02-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_remove_reservation_birth_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="id_document",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="income_proof",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="proof_of_address",
        ),
    ]
