# Generated by Django 6.0.2 on 2026-03-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_reservation_validated_at_reservation_validated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="identity_document",
            field=models.FileField(
                blank=True, null=True, upload_to="reservations/documents/"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="proof_of_address",
            field=models.FileField(
                blank=True, null=True, upload_to="reservations/documents/"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="rental_options",
            field=models.JSONField(
                blank=True,
                help_text="Options sélectionnées pour la location",
                null=True,
            ),
        ),
    ]
