# Generated by Django 6.0.2 on 2026-02-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("engine", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("color", models.CharField(max_length=50)),
                ("mileage", models.PositiveIntegerField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("purchase", "Achat"), ("rental", "Location")],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
