# Generated by Django 6.0.2 on 2026-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicle_main_image_vehicleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
