# Generated by Django 6.0.2 on 2026-02-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_alter_vehicle_vehicle_type_alter_vehicle_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["-created_at"]},
        ),
    ]
