# Generated by Django 6.0.2 on 2026-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_alter_vehicle_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Mettre en avant sur la page d'accueil"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponible"),
                    ("reserved", "Réservé"),
                    ("sold", "Vendu"),
                ],
                db_index=True,
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="is_main",
            field=models.BooleanField(
                default=False, help_text="Définir comme image principale"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["price"], name="vehicles_ve_price_da359f_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["year"], name="vehicles_ve_year_656e54_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["status"], name="vehicles_ve_status_f71f77_idx"),
        ),
    ]
